# This code was generated by a tool.
# ility@0.0.3
#
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated.

# typed: strict

require 'typed_struct_helper'

module IlityExample::V1
  class CreateGizmoSize < T::Enum
    enums do
      SMALL = new('small')
      MEDIUM = new('medium')
      BIG = new('big')
      XL = new('XL')
    end
  end
end
