# This code was generated by a tool.
# ility@0.0.3
#
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated.

# typed: strict

require 'typed_struct_helper'

module IlityExample::V1::GizmoService
  extend T::Sig
  extend T::Helpers

  interface!

  sig do
    abstract.params(search: T.nilable(String)).
      returns(IlityExample::V1::GizmosResponse)
  end
  def get_gizmos(search: nil)
  end

  sig do
    abstract.params(size: T.nilable(IlityExample::V1::CreateGizmoSize)).
      returns(IlityExample::V1::Gizmo)
  end
  def create_gizmo(size: nil)
  end

  sig do
    abstract.params(factors: T.nilable(T::Array[String])).
      returns(IlityExample::V1::Gizmo)
  end
  def update_gizmo(factors: nil)
  end
end