# This code was generated by a tool.
# ility@{{version}}
#
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated.

# typed: strict

require 'typed_struct_helper'

module IlityExample::V1
  class ValidationError < T::Struct
    extend T::Sig
    include TypedStructHelper

    const :code, T.nilable(String)
    const :title, T.nilable(String)
    const :path, T.nilable(String)
  end
end
